apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-d2bu
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-e2e-pyxis-tenant/appstudio/dc-metro-map-d2bu@sha256:371a85e97056e57bab7b6b08f206334a8dcfe7447cc17746215b05b84febd68f
        name: my-nodejs
        resources: {}
status: {}
